export const FETCH_FLIGHT_REQUEST = 'FETCH_FLIGHT_REQUEST';
export const FETCH_FLIGHT_SUCCESS = 'FETCH_FLIGHT_SUCCESS';
export const FETCH_FLIGHT_FAILURE = 'FETCH_FLIGHT_FAILURE';

export const EDIT_FLIGHT_REQUEST = 'EDIT_FLIGHT_REQUEST';
export const EDIT_FLIGHT_SUCCESS = 'EDIT_FLIGHT_SUCCESS';
export const EDIT_FLIGHT_FAILURE = 'EDIT_FLIGHT_FAILURE';

export const CREATE_FLIGHT_REQUEST = 'CREATE_FLIGHT_REQUEST';
export const CREATE_FLIGHT_SUCCESS = 'CREATE_FLIGHT_SUCCESS';
export const CREATE_FLIGHT_FAILURE = 'CREATE_FLIGHT_FAILURE';

export const DELETE_FLIGHT_REQUEST = 'DELETE_FLIGHT_REQUEST';
export const DELETE_FLIGHT_SUCCESS = 'DELETE_FLIGHT_SUCCESS';
export const DELETE_FLIGHT_FAILURE = 'DELETE_TODO_FAILURE';
